# Climate Coding Challenge

Climate change is impacting the way people live around the world


## Set up

To get started on this notebook, you’ll need to restore any variables
from previous notebooks to your workspace. To save time and memory, make
sure to specify which variables you want to load.

In [1]:
%store -r

You will also need to import any libraries you are using in this
notebook, since they won’t carry over from the previous notebook:

In [ ]:
### import libraries

### Step 1E: Convert the units

It’s important to keep track of the units of all your data. You don’t want to be like the [NASA team who crashed a probe into Mars because different teams used different units](https://www.latimes.com/archives/la-xpm-1999-oct-01-mn-17288-story.html))!

One way to keep track of your data’s units is to include the unit in
data **labels**. In the case of a `DataFrame`, that usually means the
column names.

<link rel="stylesheet" type="text/css" href="./assets/styles.css"><div class="callout callout-style-default callout-titled callout-task"><div class="callout-header"><div class="callout-icon-container"><i class="callout-icon"></i></div><div class="callout-title-container flex-fill"></div></div><div class="callout-body-container callout-body"><p>A big part of writing <strong>expressive</strong> code is descriptive
labels. Let’s rename the columns of your dataframe to include units.
Complete the following steps:</p>
<ol type="1">
<li>Replace <code>dataframe</code> with the name of
<strong>your</strong> <code>DataFrame</code>, and
<code>dataframe_units</code> with an expressive new name.</li>
<li>Check out the <a
href="https://www.ncei.noaa.gov/data/global-historical-climatology-network-daily/doc/GHCND_documentation.pdf">documentation
for GCHNd data</a>. We downloaded data with “standard” units; find out
what that means for temperature.</li>
<li>Replace <code>'temperature_column_name'</code> with the temperature column name in your
data, and <code>'temp_unit'</code> with a column name that includes the
correct unit. For example, you could make a column called <code>'temperature_k'</code> to note that your degrees are in Kelvin. </li>
</ol></div></div>

In [ ]:
dataframe_units = dataframe.rename(columns={
    'temperature-column-name': 'temp_unit',
})

dataframe_units

            TOBS_fahrenheit
DATE
1893-10-01              NaN
1893-10-02              NaN
1893-10-03              NaN
1893-10-04              NaN
1893-10-05              NaN
...                     ...
2023-09-26             74.0
2023-09-27             69.0
2023-09-28             73.0
2023-09-29             66.0
2023-09-30             78.0

[45971 rows x 1 columns]

**For scientific applications, it is often useful to have values in metric units**
In this case, we want to convert data from degrees Fahrenheit to degrees Celcius. The equation for converting Fahrenheit temperature to Celsius is:

`T_C = (T_F - 32) * (5/9)`
<link rel="stylesheet" type="text/css" href="./assets/styles.css"><div class="callout callout-style-default callout-titled callout-task"><div class="callout-header"><div class="callout-icon-container"><i class="callout-icon"></i></div><div class="callout-title-container flex-fill"></div></div><div class="callout-body-container callout-body"><p>The code below attempts to convert the data to Celsius, using Python mathematical <strong>operators</strong>, like <code>+</code>,
<code>-</code>, <code>*</code>, and <code>/</code>. Mathematical operators in Python work just like a calculator, and that includes using parentheses to designat the <strong>order of operations</strong>. 
<p>This code is not well documented and doesn’t follow <a
href="https://peps.python.org/pep-0008/#other-recommendations">PEP-8 guidelines</a>, which has caused the author to miss an <strong>important error</strong>!</p>
<p>Complete the following steps:</p>
<ol type="1">
<li>Replace <code>dataframe</code> with the name of
<strong>your</strong> <code>DataFrame</code>.</li>
<li>Replace <code>'old_temperature'</code> with the column name
<strong>you</strong> used; Replace <code>'new_temperature'</code> with
an <strong>expressive</strong> column name.</li>
<li>Find and fix the error in the conversion math.</li>
</ol></div></div>

In [ ]:
dataframe_units['new_temperature']= (dataframe_units['old_temperature']-32)*5/9
dataframe_units

            TOBS_fahrenheit  TOBS_celsius
DATE
1893-10-01              NaN           NaN
1893-10-02              NaN           NaN
1893-10-03              NaN           NaN
1893-10-04              NaN           NaN
1893-10-05              NaN           NaN
...                     ...           ...
2023-09-26             74.0     23.333333
2023-09-27             69.0     20.555556
2023-09-28             73.0     22.777778
2023-09-29             66.0     18.888889
2023-09-30             78.0     25.555556

[45971 rows x 2 columns]

**Looking for an extra challenge?** Using the code below as a framework, write and apply a <strong>function</strong> that converts to Celsius. You should also rewrite this function name to be more expressive.</p></div></div>

In [ ]:
### cnvert units with a function
def convert(temperature):
    """Convert temperature to Celsius"""
    return ### put your equation here

dataframe['TEMP_C'] = (
    dataframe['TEMP_F'].apply(convert))

# Wrap up Step 1E

Don’t forget to store your variables so you can use them in other notebooks! Replace `var1` and `var2` with the variable you want to save, separated by spaces.

In [ ]:
%store

Stored 'climate_df' (DataFrame)
Stored 'climate_units_df' (DataFrame)

Finally, be sure to `Restart` and `Run all` to make sure your notebook
works all the way through!